spring:
  application:
    name: Spring-Secuurity-OAuth-App

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: {github client ID}
            client-secret: {github client Secret}



