spring:
  application:
    name: Spring-Secuurity-OAuth-App

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: Ov23li6HkpJokV6jbINb
            client-secret: 85ba58ac7372814289d41d87b9b9d026efa68aa3